// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vPacket.proto
#ifndef GRPC_vPacket_2eproto__INCLUDED
#define GRPC_vPacket_2eproto__INCLUDED

#include "vPacket.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace videoencoding {

class VideoEncodingService final {
 public:
  static constexpr char const* service_full_name() {
    return "videoencoding.VideoEncodingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::videoencoding::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>> AsyncGetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>>(AsyncGetStringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>> PrepareAsyncGetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>>(PrepareAsyncGetStringRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetString(::grpc::ClientContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetString(::grpc::ClientContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>* AsyncGetStringRaw(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::videoencoding::Response>* PrepareAsyncGetStringRaw(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::videoencoding::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>> AsyncGetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>>(AsyncGetStringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>> PrepareAsyncGetString(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>>(PrepareAsyncGetStringRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetString(::grpc::ClientContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response, std::function<void(::grpc::Status)>) override;
      void GetString(::grpc::ClientContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>* AsyncGetStringRaw(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::videoencoding::Response>* PrepareAsyncGetStringRaw(::grpc::ClientContext* context, const ::videoencoding::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetString_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetString(::grpc::ServerContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetString() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetString(::grpc::ServerContext* context, ::videoencoding::Request* request, ::grpc::ServerAsyncResponseWriter< ::videoencoding::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetString<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetString() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::videoencoding::Request, ::videoencoding::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::videoencoding::Request* request, ::videoencoding::Response* response) { return this->GetString(context, request, response); }));}
    void SetMessageAllocatorFor_GetString(
        ::grpc::MessageAllocator< ::videoencoding::Request, ::videoencoding::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::videoencoding::Request, ::videoencoding::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetString(
      ::grpc::CallbackServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetString<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetString() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetString() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetString(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetString() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetString(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetString(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetString() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::videoencoding::Request, ::videoencoding::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::videoencoding::Request, ::videoencoding::Response>* streamer) {
                       return this->StreamedGetString(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetString(::grpc::ServerContext* /*context*/, const ::videoencoding::Request* /*request*/, ::videoencoding::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetString(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::videoencoding::Request,::videoencoding::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetString<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetString<Service > StreamedService;
};

}  // namespace videoencoding


#endif  // GRPC_vPacket_2eproto__INCLUDED
